databases:
  - name: mcdonaldsorderingdb
    plan: free
    databaseName: mcdonaldsordering
    user: admin

services:
  - type: web
    plan: free
    name: mcdonaldsordering
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mcdonaldsordering.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mcdonaldsorderingdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
